window.QUESTS_POOL = [

    // ── EASY (1000 XP) ─────────────────────────────────────────────────────────

    { title: "Mangia al buio", description: "Consuma un pasto completo bendato o a luci completamente spente. Ogni boccone diventa un'esperienza sensoriale nuova.", difficulty: "easy", xp: 1000 },
    { title: "Scrivi una lettera a mano", description: "Scrivi una lettera vera, su carta, a qualcuno che non senti da almeno un anno. Non mandarla via email.", difficulty: "easy", xp: 1000 },
    { title: "Cibo scelto dagli altri", description: "Lascia che un'altra persona ordini o prepari ogni tuo pasto per un'intera giornata. Zero veto.", difficulty: "easy", xp: 1000 },
    { title: "Alzati con il sole", description: "Svegliati prima dell'alba, esci fuori e guarda il sole sorgere senza schermo in mano.", difficulty: "easy", xp: 1000 },
    { title: "Giornata senza specchi", description: "Passa 24 ore senza guardarti in nessuno specchio o fotocamera frontale.", difficulty: "easy", xp: 1000 },
    { title: "Disegna qualcosa dal vero", description: "Siediti davanti a un oggetto o paesaggio e disegnalo su carta. Non importa quanto sei bravo.", difficulty: "easy", xp: 1000 },
    { title: "Cammina scalzo in natura", description: "Fai almeno 20 minuti di camminata a piedi nudi su terra, erba o sabbia.", difficulty: "easy", xp: 1000 },
    { title: "Chiedi a uno sconosciuto un consiglio", description: "Avvicina una persona che non conosci e chiedi un consiglio su qualsiasi cosa, genuinamente.", difficulty: "easy", xp: 1000 },
    { title: "Cucina senza ricetta", description: "Prepara un pasto completo usando solo quello che hai in casa, senza consultare nessuna ricetta.", difficulty: "easy", xp: 1000 },
    { title: "Leggi ad alta voce", description: "Leggi un capitolo di un libro o un articolo lungo ad alta voce, come se recitassi per un pubblico.", difficulty: "easy", xp: 1000 },
    { title: "Fai qualcosa con la mano non dominante", description: "Per un'intera mattinata usa solo la mano che usi meno: mangia, scrivi, apri le porte.", difficulty: "easy", xp: 1000 },
    { title: "Parla con il vicino che non conosci", description: "Bussa alla porta del vicino più prossimo che non hai mai salutato e presentati davvero.", difficulty: "easy", xp: 1000 },
    { title: "Fai una donazione anonima", description: "Lascia qualcosa di valore (soldi, cibo, oggetti) in un posto dove qualcuno lo troverà, senza firma.", difficulty: "easy", xp: 1000 },
    { title: "Ascolta un album per intero", description: "Scegli un album che non hai mai sentito, sdraiati, chiudi gli occhi e ascoltalo dall'inizio alla fine senza distrazioni.", difficulty: "easy", xp: 1000 },
    { title: "Costruisci qualcosa con le mani", description: "Usa materiali che hai in casa per costruire qualcosa di fisico — non importa cosa, l'importante è che funzioni.", difficulty: "easy", xp: 1000 },
    { title: "Vai a letto a un orario impossibile", description: "Coricati entro le 21:30 una sera e dormi fino a svegliarti naturalmente, senza sveglia.", difficulty: "easy", xp: 1000 },
    { title: "Fotografa solo ombre per un giorno", description: "Esci con il telefono e scatta foto solo di ombre. Alla fine scegli la migliore.", difficulty: "easy", xp: 1000 },
    { title: "Mangia qualcosa che non hai mai assaggiato", description: "Trova un alimento che non hai mai messo in bocca in vita tua e mangialo, davvero.", difficulty: "easy", xp: 1000 },
    { title: "Passa un pomeriggio in silenzio totale", description: "Niente musica, niente podcast, niente video. Solo tu e i suoni di ciò che ti circonda per almeno 3 ore.", difficulty: "easy", xp: 1000 },
    { title: "Scrivi 10 cose che sai fare", description: "Siediti e scrivi, senza fermarti, dieci abilità che possiedi. Anche le più banali contano.", difficulty: "easy", xp: 1000 },
    { title: "Prendi un autobus a caso", description: "Sali sul primo autobus che passa, vai fino al capolinea e poi torna. Nessun piano.", difficulty: "easy", xp: 1000 },
    { title: "Dormi all'aperto nel tuo giardino", description: "Se hai accesso a uno spazio esterno, porta il tuo materasso o un sacco a pelo e dormi fuori.", difficulty: "easy", xp: 1000 },
    { title: "Impara una poesia a memoria", description: "Scegli una poesia breve e imparala a memoria. Recitala alla fine del giorno senza guardare il testo.", difficulty: "easy", xp: 1000 },
    { title: "Chiama qualcuno solo per dirgli grazie", description: "Pensa a qualcuno che non hai mai ringraziato davvero. Chiamalo. Solo per quello.", difficulty: "easy", xp: 1000 },
    { title: "Cammina per un'ora senza meta", description: "Esci di casa e cammina per almeno 60 minuti seguendo solo il tuo istinto a ogni bivio.", difficulty: "easy", xp: 1000 },
    { title: "Passa una mattina senza telefono", description: "Dalla sveglia fino a pranzo, tieni il telefono spento o in un'altra stanza.", difficulty: "easy", xp: 1000 },
    { title: "Fai un complimento sincero a 5 persone", description: "Nell'arco della giornata, fai un complimento genuino e specifico a cinque persone diverse.", difficulty: "easy", xp: 1000 },
    { title: "Guarda le stelle per 30 minuti", description: "Trova un posto buio, sdraiati e guarda il cielo notturno per almeno mezz'ora senza guardare il telefono.", difficulty: "easy", xp: 1000 },
    { title: "Fai una doccia fredda", description: "Completa la tua doccia normale con almeno 3 minuti di acqua completamente fredda.", difficulty: "easy", xp: 1000 },
    { title: "Scrivi il tuo necrologio ideale", description: "Scrivi come vorresti essere ricordato. Non quello che sei ora, quello che vuoi diventare.", difficulty: "easy", xp: 1000 },
    { title: "Vai al cinema da solo", description: "Scegli un film in programmazione e vai al cinema completamente da solo. Siediti dove vuoi.", difficulty: "easy", xp: 1000 },
    { title: "Fai colazione in un posto insolito", description: "Porta la colazione sul tetto, in giardino, in un parco, su una panchina lontana da casa — da qualche parte inaspettata.", difficulty: "easy", xp: 1000 },
    { title: "Impara 10 parole in una lingua sconosciuta", description: "Scegli una lingua che non conosci per niente e impara 10 parole davvero, non solo leggerle.", difficulty: "easy", xp: 1000 },
    { title: "Trova la cosa più vecchia che possiedi", description: "Cerca in casa l'oggetto più antico che hai. Scopri da dove viene e scrivine la storia.", difficulty: "easy", xp: 1000 },
    { title: "Mangia lentissimo", description: "Prenditi almeno 45 minuti per consumare un pasto. Posa le posate tra ogni boccone.", difficulty: "easy", xp: 1000 },
    { title: "Fai un disegno con gli occhi chiusi", description: "Pensa a qualcosa e disegnalo senza mai aprire gli occhi. Guarda il risultato solo alla fine.", difficulty: "easy", xp: 1000 },
    { title: "Rifiuta qualcosa che normalmente accetteresti", description: "Oggi di' no a qualcosa che solitamente fai per abitudine o per compiacere gli altri.", difficulty: "easy", xp: 1000 },
    { title: "Esplora il tuo quartiere come un turista", description: "Gira per il tuo quartiere come se fosse la prima volta che ci sei. Fotografa tutto quello che trovi interessante.", difficulty: "easy", xp: 1000 },
    { title: "Prepara un pasto per qualcuno a sorpresa", description: "Cucina qualcosa e portalo a qualcuno senza preavviso. Non aspettarti niente in cambio.", difficulty: "easy", xp: 1000 },
    { title: "Scrivi 3 pagine di flusso di coscienza", description: "Appena sveglio, scrivi tre pagine a mano senza fermarti e senza correggere nulla.", difficulty: "easy", xp: 1000 },
    { title: "Fai un bagno nel mare o in un lago", description: "Entra in un'acqua naturale anche solo per qualche minuto, indipendentemente dalla temperatura.", difficulty: "easy", xp: 1000 },
    { title: "Stai in piedi per un'intera mattinata", description: "Dalla sveglia fino a pranzo non sederti mai. Lavora, mangia, leggi tutto in piedi.", difficulty: "easy", xp: 1000 },
    { title: "Incontra qualcuno senza consultare il telefono", description: "Quando incontri qualcuno, lascia il telefono in tasca per l'intera durata dell'incontro.", difficulty: "easy", xp: 1000 },
    { title: "Fai una mappa del tuo quartiere a memoria", description: "Disegna una mappa del tuo quartiere a memoria, il più dettagliata possibile. Poi vai a verificare.", difficulty: "easy", xp: 1000 },
    { title: "Ascolta un genere musicale che odi", description: "Metti su un'ora di musica di un genere che normalmente salteresti. Cerca di trovarci qualcosa.", difficulty: "easy", xp: 1000 },
    { title: "Vai a dormire senza aver guardato schermi", description: "Nell'ultima ora prima di dormire, zero schermi. Leggi, scrivi, ascolta, pensa.", difficulty: "easy", xp: 1000 },
    { title: "Trova un posto nuovo in città", description: "Cerca e visita un luogo della tua città che non hai mai visitato nonostante ci vivi.", difficulty: "easy", xp: 1000 },
    { title: "Impara a fischiare in modo diverso", description: "Impara una tecnica di fischio che non conosci — con le dita, con la lingua, a bocca chiusa.", difficulty: "easy", xp: 1000 },
    { title: "Mangia un pasto completamente in silenzio", description: "Siediti a tavola, mangia lentamente e in totale silenzio. Niente musica, niente conversazioni.", difficulty: "easy", xp: 1000 },
    { title: "Scrivi una storia di esattamente 100 parole", description: "Racconta qualcosa in esattamente 100 parole — non 99, non 101. Deve avere inizio, svolgimento e fine.", difficulty: "easy", xp: 1000 },
    { title: "Guarda un tramonto fino alla fine", description: "Siediti e osserva un tramonto dall'inizio alla fine, senza interrompere per foto o messaggi.", difficulty: "easy", xp: 1000 },
    { title: "Fai 30 minuti di meditazione", description: "Siediti in silenzio, chiudi gli occhi e rimani immobile per 30 minuti. Nessuna guida audio.", difficulty: "easy", xp: 1000 },
    { title: "Visita una mostra gratuita", description: "Trova una mostra, esposizione o evento culturale gratuito nella tua zona e vai.", difficulty: "easy", xp: 1000 },
    { title: "Leggi per due ore di fila", description: "Due ore di lettura ininterrotta. Solo libri, zero articoli, zero scroll.", difficulty: "easy", xp: 1000 },
    { title: "Chiedi scusa a qualcuno", description: "Pensa a qualcuno a cui devi delle scuse che non hai mai dato. Fallo oggi.", difficulty: "easy", xp: 1000 },
    { title: "Cucina qualcosa che non hai mai cucinato", description: "Trova una ricetta di un piatto che non hai mai preparato e portala a termine.", difficulty: "easy", xp: 1000 },
    { title: "Fai stretching per 20 minuti", description: "Dedicati allo stretching profondo per 20 minuti, concentrandoti sui punti più rigidi del corpo.", difficulty: "easy", xp: 1000 },
    { title: "Porta con te un taccuino per un giorno", description: "Tieni un taccuino in tasca e scrivi ogni pensiero, osservazione o idea che ti viene durante la giornata.", difficulty: "easy", xp: 1000 },
    { title: "Mangia vegetariano per un giorno intero", description: "24 ore senza carne né pesce. Scopri quanto sei creativo con le alternative.", difficulty: "easy", xp: 1000 },
    { title: "Fai qualcosa di utile per il tuo edificio o condominio", description: "Pulisci le scale, sistema il giardino condominiale, aggiusta qualcosa — senza che te lo chieda nessuno.", difficulty: "easy", xp: 1000 },
    { title: "Guarda un film in lingua originale senza sottotitoli", description: "Scegli un film in una lingua che capisci appena. Guardalo fino in fondo senza sottotitoli.", difficulty: "easy", xp: 1000 },
    { title: "Scrivi una recensione sincera", description: "Scrivi una recensione onesta e dettagliata di qualcosa che hai vissuto di recente — un posto, un prodotto, un'esperienza.", difficulty: "easy", xp: 1000 },
    { title: "Impara il nome di tre costellazioni", description: "Studia tre costellazioni, poi esci di notte e trovale davvero nel cielo.", difficulty: "easy", xp: 1000 },
    { title: "Svuota un cassetto", description: "Scegli il cassetto più caotico di casa tua. Svuotalo completamente, tieni solo quello che usi davvero.", difficulty: "easy", xp: 1000 },
    { title: "Cammina contromano", description: "In un percorso che fai di solito, fallo al contrario, partendo dalla fine e tornando all'inizio.", difficulty: "easy", xp: 1000 },
    { title: "Fai una conversazione profonda con qualcuno", description: "Parla con qualcuno per almeno un'ora di qualcosa che conta davvero — non gossip, non meteo, non lavoro.", difficulty: "easy", xp: 1000 },
    { title: "Non lamentarti per un giorno intero", description: "Vivi l'intera giornata senza esprimere nessuna lamentela — né ad alta voce né nella tua testa.", difficulty: "easy", xp: 1000 },
    { title: "Fai una telefonata invece di scrivere", description: "Per ogni messaggio che stai per mandare durante la giornata, chiama invece quella persona.", difficulty: "easy", xp: 1000 },
    { title: "Siediti in un bar e guarda la gente passare", description: "Siediti a un tavolino all'aperto per almeno 45 minuti. Osserva. Niente telefono.", difficulty: "easy", xp: 1000 },
    { title: "Impara a fare un nodo marinaro", description: "Impara almeno tre nodi marinari diversi fino a saperli fare a occhi chiusi.", difficulty: "easy", xp: 1000 },
    { title: "Fai qualcosa che hai rimandato da mesi", description: "Identifica la cosa che stai rimandando da più tempo e falla tutta, completamente, oggi.", difficulty: "easy", xp: 1000 },
    { title: "Passa una sera senza internet", description: "Dalla cena in poi, niente connessione a internet fino al mattino dopo.", difficulty: "easy", xp: 1000 },
    { title: "Regala qualcosa a cui tieni", description: "Scegli un oggetto a cui sei affezionato e regalalo a qualcuno che pensi lo apprezzerebbe.", difficulty: "easy", xp: 1000 },
    { title: "Vai a lavorare o studiare in un posto insolito", description: "Porta laptop o libri in un posto dove non hai mai lavorato — una chiesa, un parco, una biblioteca diversa.", difficulty: "easy", xp: 1000 },
    { title: "Impara 5 fatti su qualcosa che ignori", description: "Scegli un argomento di cui sai zero e studia finché non hai almeno 5 fatti solidi.", difficulty: "easy", xp: 1000 },
    { title: "Fai un'ora di servizio volontario", description: "Offri un'ora del tuo tempo a qualcuno o qualcosa che ne ha bisogno, senza aspettarti nulla.", difficulty: "easy", xp: 1000 },

    // ── MEDIUM (2000 XP) ───────────────────────────────────────────────────────

    { title: "Esplora un luogo abbandonato", description: "Trova un edificio, fabbrica o posto abbandonato nella tua zona e esploralo in sicurezza. Porta una torcia.", difficulty: "medium", xp: 2000 },
    { title: "Fai campeggio una notte con gli amici", description: "Organizza una notte in tenda fuori dalla città con almeno un'altra persona. Niente hotel, niente B&B.", difficulty: "medium", xp: 2000 },
    { title: "Escursione senza musica", description: "Fai un'escursione di almeno 3 ore in un contesto naturale senza cuffie, musica o podcast. Solo i suoni intorno a te.", difficulty: "medium", xp: 2000 },
    { title: "Parla con uno sconosciuto per più di 30 minuti", description: "Inizia una conversazione con qualcuno che non hai mai visto prima e vai avanti finché non si crea una connessione reale.", difficulty: "medium", xp: 2000 },
    { title: "Nuota in acque aperte", description: "Nuota in mare, lago o fiume aperto per almeno 20 minuti. Senza bordo vasca, senza fondo visibile.", difficulty: "medium", xp: 2000 },
    { title: "Vai in un posto che conosci solo da internet", description: "Scegli un luogo che hai visto solo su foto o video e vai a vederlo di persona.", difficulty: "medium", xp: 2000 },
    { title: "Fai un viaggio in treno senza meta precisa", description: "Compra un biglietto per una stazione a caso, esplora il posto per qualche ora e torna.", difficulty: "medium", xp: 2000 },
    { title: "Impara a cucinare un piatto straniero complesso", description: "Scegli un piatto di una cucina che non è la tua e cucinalo dall'inizio con ingredienti originali.", difficulty: "medium", xp: 2000 },
    { title: "Partecipa a un evento locale dove non conosci nessuno", description: "Vai a una serata, sagra, mercato o evento della tua zona senza conoscere nessuno. Rimani almeno 2 ore.", difficulty: "medium", xp: 2000 },
    { title: "Fai una giornata senza soldi", description: "Passa 24 ore senza spendere un centesimo. Né fisici né digitali. Arrangiati con quello che hai.", difficulty: "medium", xp: 2000 },
    { title: "Impara un'abilità artigianale di base", description: "Dedicati a imparare qualcosa con le mani: lavorazione del legno, ceramica, ricamo, saldatura. Produci qualcosa.", difficulty: "medium", xp: 2000 },
    { title: "Trascorri una giornata intera in una città che non conosci", description: "Scegli una città che non hai mai visitato e passa lì l'intera giornata da solo, senza itinerario.", difficulty: "medium", xp: 2000 },
    { title: "Fai il bagno in un fiume di montagna", description: "Trova un corso d'acqua naturale freddo e immergiti completamente, anche solo per qualche secondo.", difficulty: "medium", xp: 2000 },
    { title: "Passa una notte in totale silenzio digitale", description: "Dalla sera alla mattina dopo: telefono spento, computer spento, nessuno schermo di nessun tipo.", difficulty: "medium", xp: 2000 },
    { title: "Partecipa a un corso di qualcosa che non sai fare", description: "Iscriviti a una singola lezione di qualcosa che non hai mai fatto — ceramica, salsa, arrampicata, falegneria.", difficulty: "medium", xp: 2000 },
    { title: "Leggi un intero libro in due giorni", description: "Scegli un libro che vuoi leggere da tempo e finiscilo nell'arco di 48 ore.", difficulty: "medium", xp: 2000 },
    { title: "Fai un'escursione notturna", description: "Esci di notte in un contesto naturale — bosco, collina, spiaggia — e cammina almeno un'ora al buio.", difficulty: "medium", xp: 2000 },
    { title: "Cucinare per 10 persone", description: "Organizza un pranzo o cena dove cucini tu per almeno 10 persone, da solo o quasi.", difficulty: "medium", xp: 2000 },
    { title: "Fai una giornata completa senza lamentele", description: "Svegliati con l'intenzione di non lamentarti di nulla per 24 ore. Ogni volta che ci stai ricaschi, riparti.", difficulty: "medium", xp: 2000 },
    { title: "Vai al mercato dell'alba", description: "Alzati prima che sorga il sole e vai al mercato ortofrutticolo o ittico della tua città all'apertura.", difficulty: "medium", xp: 2000 },
    { title: "Percorri un sentiero che non hai mai fatto", description: "Cerca un sentiero segnato nella tua regione che non hai mai percorso e completalo dall'inizio alla fine.", difficulty: "medium", xp: 2000 },
    { title: "Fai un ritratto a matita di qualcuno", description: "Siediti davanti a una persona reale e disegnane il ritratto a matita. Almeno 30 minuti di lavoro.", difficulty: "medium", xp: 2000 },
    { title: "Trascorri una giornata senza usare la macchina", description: "Muoviti solo a piedi, bici o mezzi pubblici per un'intera giornata, qualunque cosa tu debba fare.", difficulty: "medium", xp: 2000 },
    { title: "Impara i rudimenti di uno strumento musicale", description: "Prendi in mano uno strumento che non sai suonare e impara almeno una melodia semplice riconoscibile.", difficulty: "medium", xp: 2000 },
    { title: "Fai una maratona di film di un regista", description: "Scegli un regista che non conosci bene e guarda almeno tre dei suoi film in sequenza.", difficulty: "medium", xp: 2000 },
    { title: "Passa un pomeriggio in una biblioteca grande", description: "Vai nella biblioteca più grande della tua zona, esplora sezioni che non avresti scelto e leggi almeno 3 ore.", difficulty: "medium", xp: 2000 },
    { title: "Fai volontariato in una mensa o banco alimentare", description: "Offri una mezza giornata del tuo tempo a servire o distribuire cibo a chi ne ha bisogno.", difficulty: "medium", xp: 2000 },
    { title: "Vai in bici per almeno 40 km", description: "Pianifica un percorso di almeno 40 km in bici. Completa tutto il tragitto.", difficulty: "medium", xp: 2000 },
    { title: "Scrivi e invia una lettera anonima di incoraggiamento", description: "Scrivi una lettera genuina di supporto a qualcuno che pensi ne abbia bisogno. Mettila in buca senza firma.", difficulty: "medium", xp: 2000 },
    { title: "Fai un'intervista a qualcuno over 70", description: "Siediti con una persona anziana — un familiare, un vicino, uno sconosciuto — e registra le sue storie di vita.", difficulty: "medium", xp: 2000 },
    { title: "Organizza una cena al buio completo", description: "Mangia con amici in totale oscurità. Niente telefoni accesi, niente candele.", difficulty: "medium", xp: 2000 },
    { title: "Impara a leggere una cartina topografica", description: "Studia una cartina topografica di un'area che conosci fino a riuscire a orientarti con essa senza GPS.", difficulty: "medium", xp: 2000 },
    { title: "Passa una giornata a fare solo cose per gli altri", description: "Per 24 ore, ogni azione che fai deve essere utile a qualcun altro. Nessun'azione egoistica.", difficulty: "medium", xp: 2000 },
    { title: "Visita un paese vicino che non hai mai visto", description: "Vai a visitare un piccolo comune o paesino entro 50 km da casa tua che non hai mai esplorato.", difficulty: "medium", xp: 2000 },
    { title: "Fai un'ora di arrampicata su roccia o indoor", description: "Prova l'arrampicata su una parete vera o in una palestra di arrampicata. Arriva almeno a metà altezza.", difficulty: "medium", xp: 2000 },
    { title: "Cucinare pane da zero", description: "Prepara il pane partendo da farina e lievito. Aspetta i tempi di lievitazione. Cuocilo. Mangialo.", difficulty: "medium", xp: 2000 },
    { title: "Trascorri un pomeriggio senza pianificare niente", description: "Esci di casa senza meta, senza programma, senza sapere cosa farai. Vai dove ti porta il caso.", difficulty: "medium", xp: 2000 },
    { title: "Fai una sessione di raccolta rifiuti in natura", description: "Porta con te dei sacchi e dedica almeno 2 ore a raccogliere rifiuti in un'area naturale abbandonata.", difficulty: "medium", xp: 2000 },
    { title: "Passa una domenica senza guardare sport", description: "Se guardi sport regolarmente, passa una domenica intera senza accendere la TV per farlo.", difficulty: "medium", xp: 2000 },
    { title: "Impara i nodi base della sopravvivenza", description: "Studia e pratica almeno 5 nodi fondamentali per la sopravvivenza fino a saperli fare senza guardare.", difficulty: "medium", xp: 2000 },
    { title: "Fai una full immersion in una lingua straniera", description: "Per un'intera giornata, consuma contenuti solo nella lingua che stai imparando: film, libri, musica, podcast.", difficulty: "medium", xp: 2000 },
    { title: "Costruisci un fuoco da zero", description: "Accendi un fuoco usando tecniche manuali o con gli strumenti minimi. Niente accendino o fiammiferi.", difficulty: "medium", xp: 2000 },
    { title: "Partecipa a una veglia o cerimonia funebre di qualcuno che non conosci bene", description: "Vai a portare rispetto a qualcuno che conoscevi appena. Rimani e parla con chi era vicino a lui.", difficulty: "medium", xp: 2000 },
    { title: "Fai un'intera giornata produttiva da un bar", description: "Lavora o studia tutto il giorno da un bar pubblico. Cambia locale a metà giornata.", difficulty: "medium", xp: 2000 },
    { title: "Impara a usare una bussola", description: "Studia come orientarsi con una bussola e una cartina. Poi vai in un posto sconosciuto e trovaci la strada.", difficulty: "medium", xp: 2000 },
    { title: "Corri 10 km senza fermarti", description: "Se non lo hai mai fatto, allenati quanto basta e poi corri 10 km consecutivi senza camminare.", difficulty: "medium", xp: 2000 },
    { title: "Impara la siglatura braille di base", description: "Studia l'alfabeto braille fino a saper scrivere il tuo nome e leggere qualche parola al tatto.", difficulty: "medium", xp: 2000 },
    { title: "Fai un viaggio da solo in moto o bici per un giorno", description: "Pianifica un percorso di almeno 100 km in moto o bici, da solo, senza destinazione obbligata.", difficulty: "medium", xp: 2000 },
    { title: "Prova la meditazione vipassana per un weekend", description: "Segui un ritiro di meditazione di almeno 2 giorni in silenzio, anche in versione domestica auto-guidata.", difficulty: "medium", xp: 2000 },
    { title: "Fai una cena etnica da zero", description: "Scegli una cucina che non hai mai cucinato — etiope, georgiana, peruviana — e prepara un pasto completo.", difficulty: "medium", xp: 2000 },
    { title: "Vai a pescare per una giornata intera", description: "Trascorri un'intera giornata a pescare, dall'alba al tramonto. Niente fretta, niente agenda.", difficulty: "medium", xp: 2000 },
    { title: "Trascorri un pomeriggio in un museo che non avresti mai scelto", description: "Vai in un museo di argomento che non ti interessa. Cerca qualcosa che ti sorprenda.", difficulty: "medium", xp: 2000 },
    { title: "Fai un'intera settimana senza alcol", description: "Se bevi regolarmente, passa 7 giorni senza toccare alcol di nessun tipo.", difficulty: "medium", xp: 2000 },
    { title: "Costruisci qualcosa di utile per casa", description: "Progetta e costruisci qualcosa di pratico per la tua casa — una mensola, un porta-oggetti, un giardino verticale.", difficulty: "medium", xp: 2000 },
    { title: "Fai una passeggiata di alba in città", description: "Svegliati prima delle 5 e cammina per la tua città quando è ancora deserta. Porta una macchina fotografica.", difficulty: "medium", xp: 2000 },
    { title: "Impara a fare il pane con lievito madre", description: "Crea il tuo lievito madre da zero, aspetta che sia pronto e usa it per fare il pane.", difficulty: "medium", xp: 2000 },
    { title: "Segui un corso online dall'inizio alla fine", description: "Scegli un corso online gratuito su qualcosa che vuoi imparare davvero e completalo tutto, non solo i primi moduli.", difficulty: "medium", xp: 2000 },
    { title: "Passa una giornata come pendolare", description: "Svegliati alle 6, prenditi i mezzi pubblici e passa la giornata fuori come farebbero milioni di lavoratori ogni giorno.", difficulty: "medium", xp: 2000 },
    { title: "Fai un'escursione di almeno 20 km", description: "Pianifica e completa un'escursione a piedi di almeno 20 km in un'unica giornata.", difficulty: "medium", xp: 2000 },
    { title: "Impara a orientarti con il sole", description: "Studia come usare il sole per orientarsi nelle diverse ore del giorno. Poi mettilo in pratica senza telefono.", difficulty: "medium", xp: 2000 },
    { title: "Scrivi un racconto breve e fallo leggere a qualcuno", description: "Scrivi un racconto di almeno due pagine e chiedi a qualcuno di leggerlo davanti a te.", difficulty: "medium", xp: 2000 },
    { title: "Fai una notte intera in bianco (intenzionale)", description: "Scegli una notte, rimani sveglio fino all'alba e usa le ore per qualcosa che hai sempre rimandato.", difficulty: "medium", xp: 2000 },
    { title: "Organizza una serata senza schermi con gli amici", description: "Riunisci degli amici per una serata senza telefoni, televisione o computer. Giocate, parlate, suonate.", difficulty: "medium", xp: 2000 },
    { title: "Impara a nuotare in modo diverso", description: "Se nuoti solo uno stile, impara a fare almeno 100 metri in un altro stile che non usi mai.", difficulty: "medium", xp: 2000 },
    { title: "Passa un'intera giornata nel bosco", description: "Dalla mattina al tramonto, stai in un contesto boschivo. Porta da mangiare, non uscire fino a sera.", difficulty: "medium", xp: 2000 },
    { title: "Fai un ritratto fotografico di qualcuno con consenso", description: "Chiedi a uno sconosciuto di fotografarlo. Passa almeno 20 minuti a lavorarci.", difficulty: "medium", xp: 2000 },

    // ── HARD (5000 XP) ─────────────────────────────────────────────────────────

    { title: "Impara un backflip in un giorno", description: "Dedica un'intera giornata ad imparare il backflip, partendo dagli esercizi preparatori fino all'esecuzione completa.", difficulty: "hard", xp: 5000 },
    { title: "Fai un viaggio in autostop", description: "Percorri almeno 200 km in autostop, senza prenotare niente in anticipo. Arrangiati con quello che trovi.", difficulty: "hard", xp: 5000 },
    { title: "Completa una maratona o mezza maratona", description: "Partecipa a una gara ufficiale di 21 o 42 km. Arriva alla fine, qualunque sia il tempo.", difficulty: "hard", xp: 5000 },
    { title: "Passa 48 ore in totale isolamento", description: "Trascorri due giorni e due notti completamente da solo, senza contatti con nessun altro essere umano.", difficulty: "hard", xp: 5000 },
    { title: "Impara a guidare una moto o una barca", description: "Prenditi le lezioni necessarie e ottieni la capacità concreta di guidare un mezzo che non sai usare.", difficulty: "hard", xp: 5000 },
    { title: "Dormi in bivacco in alta montagna", description: "Trascorri una notte in quota sopra i 2000 metri in bivacco o tenda, senza rifugio.", difficulty: "hard", xp: 5000 },
    { title: "Fai un viaggio in un paese straniero da solo", description: "Organizza e completa un viaggio di almeno 4 giorni in un paese che non hai mai visitato, completamente da solo.", difficulty: "hard", xp: 5000 },
    { title: "Impara a fare il pane a lievitazione naturale da zero", description: "Crea il tuo lievito madre, aspetta una settimana e produci un pane autentico usando solo farina, acqua, sale.", difficulty: "hard", xp: 5000 },
    { title: "Scala una vetta di almeno 3000 metri", description: "Raggiungi la cima di una montagna di almeno 3000 metri partendo dal basso, senza impianti di risalita.", difficulty: "hard", xp: 5000 },
    { title: "Partecipa a un torneo sportivo amatoriale", description: "Iscriviti a un torneo di qualsiasi sport e gareggia almeno nelle fasi eliminatorie.", difficulty: "hard", xp: 5000 },
    { title: "Fai un ritiro di meditazione di 3 giorni", description: "Partecipa o organizza da solo un ritiro di 3 giorni in silenzio, senza telefono e senza distrazioni.", difficulty: "hard", xp: 5000 },
    { title: "Impara a fare il fuoco con il metodo del bastone da fuoco", description: "Impara la tecnica del drill a mano e accendi un fuoco vero con solo legno e braccia, senza attrezzature moderne.", difficulty: "hard", xp: 5000 },
    { title: "Attraversa un'intera regione a piedi", description: "Pianifica e percorri un itinerario che attraversi tutta una regione italiana a piedi in più giorni.", difficulty: "hard", xp: 5000 },
    { title: "Impara a fare surf o kitesurf", description: "Prendi lezioni e riesci a stare in piedi sulla tavola da solo, anche solo per qualche secondo.", difficulty: "hard", xp: 5000 },
    { title: "Scrivi e pubblica qualcosa", description: "Scrivi un pezzo — racconto, saggio, articolo — e pubblicalo da qualche parte dove altri possano leggerlo.", difficulty: "hard", xp: 5000 },
    { title: "Fai 100 km in bici in un giorno solo", description: "Pianifica un percorso di 100 km e completalo in un'unica giornata senza assistenza esterna.", difficulty: "hard", xp: 5000 },
    { title: "Impara un brano musicale completo su uno strumento", description: "Prendi uno strumento e studia un brano dall'inizio alla fine fino a suonarlo senza errori davanti a qualcuno.", difficulty: "hard", xp: 5000 },
    { title: "Trascorri una settimana senza zuccheri aggiunti", description: "Per 7 giorni, zero zuccheri aggiunti in nessuna forma: no dolci, no bevande zuccherate, no succhi, no salse.", difficulty: "hard", xp: 5000 },
    { title: "Fai una traversata in kayak", description: "Percorri almeno 30 km in kayak su acqua aperta o fiume in un'unica uscita.", difficulty: "hard", xp: 5000 },
    { title: "Costruisci qualcosa di complesso con le mani", description: "Costruisci qualcosa di funzionante da zero — un mobile, uno skateboard, un arco, una chitarra — senza kit preassemblati.", difficulty: "hard", xp: 5000 },
    { title: "Partecipa a un evento di public speaking", description: "Prendi la parola in pubblico davanti ad almeno 50 persone su un argomento che conosci bene.", difficulty: "hard", xp: 5000 },
    { title: "Cammina sul Cammino di Santiago per almeno 5 giorni", description: "Percorri almeno 100 km di qualsiasi tratto del Cammino di Santiago con zaino in spalla.", difficulty: "hard", xp: 5000 },
    { title: "Impara a fare free diving", description: "Fai un corso di apnea e riesci a scendere ad almeno 10 metri di profondità in apnea.", difficulty: "hard", xp: 5000 },
    { title: "Vivi una settimana senza comprare niente", description: "Per 7 giorni, acquista zero cose non essenziali. Usa solo quello che hai. Niente cibo da asporto.", difficulty: "hard", xp: 5000 },
    { title: "Fai un trekking di più giorni in autonomia", description: "Parti con tenda, cibo e tutto il necessario e percorri almeno 3 giorni di trekking in totale autonomia.", difficulty: "hard", xp: 5000 },
    { title: "Impara a fare parkour di base", description: "Studia i movimenti fondamentali del parkour fino a riuscire a percorrere un tracciato urbano con fluidità.", difficulty: "hard", xp: 5000 },
    { title: "Trascorri una settimana senza social media", description: "7 giorni senza aprire nessun social network, incluse le app di messaggistica se le usi compulsivamente.", difficulty: "hard", xp: 5000 },
    { title: "Impara a fare fermentazione domestica", description: "Impara a fermentare kombucha, kefir o crauti e produci almeno 3 lotti diversi andati a buon fine.", difficulty: "hard", xp: 5000 },
    { title: "Fai una notte in un posto completamente selvaggio", description: "Dormi da solo in un posto che non ha nessuna struttura umana nei dintorni: foresta, deserto, alta quota.", difficulty: "hard", xp: 5000 },
    { title: "Parla in pubblico del tuo errore più grande", description: "Trova un contesto — un evento, un podcast, una riunione — e racconta pubblicamente un fallimento che non hai mai condiviso.", difficulty: "hard", xp: 5000 },
    { title: "Impara a fare una capriola aerea (aerial cartwheel)", description: "Impara il movimento aereo base senza mani, con guida di un istruttore se necessario.", difficulty: "hard", xp: 5000 },
    { title: "Trascorri 72 ore senza guardare l'orologio", description: "Tre giorni interi senza controllare mai l'ora. Niente telefono, niente orologio, niente orari.", difficulty: "hard", xp: 5000 },
    { title: "Fai un viaggio da solo in treno attraverso l'Europa", description: "Prendi il treno e attraversa almeno 3 paesi europei diversi in un viaggio continuativo.", difficulty: "hard", xp: 5000 },
    { title: "Impara a fare la ruota senza mani", description: "Esercitati fino a riuscire a fare una ruota laterale senza appoggiare le mani a terra.", difficulty: "hard", xp: 5000 },
    { title: "Pianifica e completa un pellegrinaggio laico", description: "Scegli un luogo con significato personale e raggiungi completamente a piedi nell'arco di più giorni.", difficulty: "hard", xp: 5000 },
    { title: "Trascorri un mese senza carne", description: "30 giorni di alimentazione completamente senza carne. Includi uova e latticini se vuoi, ma zero carne.", difficulty: "hard", xp: 5000 },
    { title: "Impara a fare uno sport da combattimento", description: "Segui almeno 20 lezioni di boxe, judo, wrestling o qualsiasi disciplina di combattimento fino a sparring leggero.", difficulty: "hard", xp: 5000 },
    { title: "Fai un'intera settimana di svegliarsi alle 5 del mattino", description: "Per 7 giorni consecutivi, svegliati entro le 5:00 e inizia la giornata con almeno un'ora di attività intenzionale.", difficulty: "hard", xp: 5000 },
    { title: "Costruisci un orto e raccogli il primo raccolto", description: "Crea un orto, anche sul balcone, e aspetta fino al primo raccolto commestibile.", difficulty: "hard", xp: 5000 },
    { title: "Fai il bagno in un lago di montagna sopra i 2000 metri", description: "Raggiungi un lago d'alta quota e immergiti completamente nell'acqua, indipendentemente dalla temperatura.", difficulty: "hard", xp: 5000 },
    { title: "Impara a fare skateboard — almeno un trick", description: "Impara a stare in piedi sullo skateboard e padroneggia almeno un trick di base come l'ollie.", difficulty: "hard", xp: 5000 },
    { title: "Scrivi e porta in scena un monologo", description: "Scrivi un monologo di almeno 5 minuti e recitalo davanti a un pubblico reale, anche piccolo.", difficulty: "hard", xp: 5000 },
    { title: "Attraversa una città a piedi da un estremo all'altro", description: "Scegli una città grande e percorrila tutta a piedi, da un confine all'altro, in un'unica giornata.", difficulty: "hard", xp: 5000 },
    { title: "Impara a fare il salto con la corda — 200 salti di fila", description: "Allenati finché non riesci a fare 200 salti consecutivi con la corda senza interruzioni.", difficulty: "hard", xp: 5000 },
    { title: "Fai un digiuno di 24 ore", description: "Passa 24 ore senza mangiare niente. Solo acqua. Nessuna emergenza medica, solo disciplina mentale.", difficulty: "hard", xp: 5000 },
    { title: "Organizza e gestisci un evento per almeno 30 persone", description: "Pianifica e gestisci da solo o quasi un evento — festa, concerto, mercatino, torneo — con almeno 30 partecipanti.", difficulty: "hard", xp: 5000 },
    { title: "Impara a fare il handstand (verticale sulle mani)", description: "Allenati fino a riuscire a stare in verticale sulle mani almeno 5 secondi senza supporto.", difficulty: "hard", xp: 5000 },
    { title: "Raggiungi una cima invernale con le ciaspole", description: "Fai una ciaspolata invernale fino a una vetta con neve, in condizioni sicure ma impegnative.", difficulty: "hard", xp: 5000 },
    { title: "Fai un campo sopravvivenza di 3 giorni", description: "Trascorri 3 giorni in natura usando solo le risorse che trovi. Poca tecnologia, pochi comfort.", difficulty: "hard", xp: 5000 },
    { title: "Impara un dialetto o una lingua minoritaria italiana", description: "Studia un dialetto o una lingua regionale italiana fino a riuscire a sostenere una conversazione di base.", difficulty: "hard", xp: 5000 },


    // ── EASY extra ─────────────────────────────────────────────────────────────
    { title: "Tieni un diario per una settimana", description: "Scrivi ogni giorno per 7 giorni di fila qualcosa che è successo, anche solo poche righe.", difficulty: "easy", xp: 1000 },
    { title: "Fai un'ora di passeggiata senza meta", description: "Esci senza destinazione e cammina per un'ora seguendo solo la curiosità a ogni incrocio.", difficulty: "easy", xp: 1000 },
    { title: "Prepara un picnic e mangiai fuori", description: "Prepara del cibo e mangia fuori casa, in un parco o su una collina, anche da solo.", difficulty: "easy", xp: 1000 },
    { title: "Guarda un documentario su un argomento che non conosci", description: "Scegli un documentario su qualcosa che non ti ha mai interessato. Guardalo per intero.", difficulty: "easy", xp: 1000 },
    { title: "Fai 50 flessioni in un'unica sessione", description: "Esegui 50 flessioni consecutive senza pause lunghe. Puoi dividerle in serie ma nella stessa sessione.", difficulty: "easy", xp: 1000 },
    { title: "Scrivi una canzone o una filastrocca", description: "Componi dei versi — anche bizzarri — su qualcosa che ti è vicino. Non deve essere perfetta.", difficulty: "easy", xp: 1000 },
    { title: "Visita un cimitero storico", description: "Passeggia in un cimitero storico, leggi le lapidi e pensa alle storie di chi c'era prima di te.", difficulty: "easy", xp: 1000 },
    { title: "Fai una cosa che ti spaventa un po'", description: "Identifica qualcosa di piccolo che tendi a evitare per paura o disagio. Falla.", difficulty: "easy", xp: 1000 },
    { title: "Cucina qualcosa di dolce da zero", description: "Prepara un dolce partendo dagli ingredienti di base, senza mix pronti o pasticcerie.", difficulty: "easy", xp: 1000 },
    { title: "Raccogli sassi o oggetti naturali e costruisci qualcosa", description: "Esci in natura, raccogli materiali e crea una piccola scultura, mandala o composizione.", difficulty: "easy", xp: 1000 },
    { title: "Vai a un mercato delle pulci", description: "Esplora un mercato dell'antiquariato o delle pulci. Non devi comprare nulla, solo guardare.", difficulty: "easy", xp: 1000 },
    { title: "Chiedi a qualcuno di raccontarti la sua storia di vita", description: "Siediti con qualcuno e chiedigli di raccontarti come è arrivato dove è adesso. Ascolta davvero.", difficulty: "easy", xp: 1000 },
    { title: "Trova tre cose belle in un posto che odi", description: "Vai in un posto che non ti piace e sforzati di trovare tre cose genuinamente belle o interessanti.", difficulty: "easy", xp: 1000 },
    { title: "Impara a fare un origami complesso", description: "Segui le istruzioni per un origami con più di 20 passaggi e portalo a termine.", difficulty: "easy", xp: 1000 },
    { title: "Fai una mappa visiva della tua vita", description: "Disegna su carta una mappa della tua vita — le connessioni, i momenti, le persone. Niente regole.", difficulty: "easy", xp: 1000 },
    { title: "Guarda l'alba da un posto che richiede uno sforzo", description: "Svegliati prima dell'alba e vai in un posto che richiede almeno 30 minuti per arrivarci.", difficulty: "easy", xp: 1000 },
    { title: "Annota ogni spesa per una settimana", description: "Tieni traccia di ogni centesimo che spendi per 7 giorni consecutivi. Poi analizza.", difficulty: "easy", xp: 1000 },
    { title: "Fai qualcosa di creativo con del cibo", description: "Realizza un'opera d'arte commestibile — una scultura, un paesaggio, un ritratto — usando solo cibo.", difficulty: "easy", xp: 1000 },
    { title: "Leggi la storia del posto dove abiti", description: "Studia la storia del tuo comune o quartiere. Trova qualcosa che non sapevi.", difficulty: "easy", xp: 1000 },
    { title: "Passa un sabato senza pianificare niente", description: "Non fissare nessun appuntamento, impegno o piano per un sabato intero. Vai a istinto.", difficulty: "easy", xp: 1000 },
    { title: "Cammina senza direzione fino a stancarti", description: "Esci e cammina finché non senti le gambe stanche. Poi siediti dove sei e goditi il panorama.", difficulty: "easy", xp: 1000 },
    { title: "Fai una conversazione in una lingua diversa dalla tua", description: "Inizia e porta avanti una conversazione minima in una lingua straniera con una persona reale.", difficulty: "easy", xp: 1000 },
    { title: "Passa una domenica senza usare il forno o i fornelli", description: "Mangia solo cibo crudo, freddo o non cucinato per un'intera domenica.", difficulty: "easy", xp: 1000 },
    { title: "Scrivi una lista di 20 cose che ti rendono felice", description: "Prenditi il tempo necessario e scrivi 20 cose concrete che ti portano gioia autentica.", difficulty: "easy", xp: 1000 },
    { title: "Fai 30 minuti di yoga o movimento consapevole", description: "Segui una routine di yoga o di movimento lento e consapevole per almeno mezz'ora.", difficulty: "easy", xp: 1000 },
    { title: "Inizia a imparare qualcosa di completamente inutile", description: "Studia qualcosa senza nessuna utilità pratica — la storia dei bottoni, il linguaggio dei segni, la cartomanzia.", difficulty: "easy", xp: 1000 },
    { title: "Racconta a qualcuno un segreto vero", description: "Condividi qualcosa che non hai mai detto a nessuno con una persona di cui ti fidi.", difficulty: "easy", xp: 1000 },
    { title: "Fai una camminata di un'ora nella pioggia", description: "Quando piove, esci comunque con abiti adatti e cammina per un'ora. Goditi i suoni e la sensazione.", difficulty: "easy", xp: 1000 },
    { title: "Crea un album fotografico fisico", description: "Stampa delle foto che hai sul telefono e crea un piccolo album fisico con note scritte a mano.", difficulty: "easy", xp: 1000 },
    { title: "Passa un pomeriggio a fare giardinaggio", description: "Dedica un pomeriggio alla cura di piante — in giardino, sul balcone o ricominciando da zero.", difficulty: "easy", xp: 1000 },

    // ── MEDIUM extra ──────────────────────────────────────────────────────────
    { title: "Prendi parte a un hackathon o jam creativa", description: "Partecipa a un evento di creazione rapida — hackathon, game jam, jam musicale — in squadra con sconosciuti.", difficulty: "medium", xp: 2000 },
    { title: "Fai una traversata di un lago a nuoto", description: "Scegli un lago e attraversalo a nuoto da una sponda all'altra, anche con supporto di accompagnamento.", difficulty: "medium", xp: 2000 },
    { title: "Trascorri un weekend senza usare i trasporti motorizzati", description: "Per 48 ore muoviti solo a piedi o in bici. Nessun mezzo a motore.", difficulty: "medium", xp: 2000 },
    { title: "Fai una sessione fotografica in bianco e nero", description: "Esci con l'intento di fotografare in bianco e nero per un'intera giornata. Stampa o mostra le tre migliori.", difficulty: "medium", xp: 2000 },
    { title: "Impara a fare corda doppia in arrampicata", description: "Impara a fare calata in corda doppia su una via reale con attrezzatura appropriata.", difficulty: "medium", xp: 2000 },
    { title: "Partecipa a un evento di narrativa orale", description: "Racconta una storia di fronte a persone che non conosci — in un open mic, un bar, un evento dedicato.", difficulty: "medium", xp: 2000 },
    { title: "Fai una settimana senza cibo confezionato", description: "Per 7 giorni mangia solo cibo cucinato da te con ingredienti freschi. Zero packaging industriale.", difficulty: "medium", xp: 2000 },
    { title: "Impara 20 chord di chitarra e suona una canzone", description: "Impara 20 accordi di chitarra e mettili insieme per suonare almeno una canzone completa.", difficulty: "medium", xp: 2000 },
    { title: "Fai jogging in un posto nuovo ogni giorno per una settimana", description: "Per 7 giorni consecutivi corri in un posto diverso ogni volta. Niente ripetizioni.", difficulty: "medium", xp: 2000 },
    { title: "Cucina un pasto per un senzatetto", description: "Prepara un pasto caldo e portalo personalmente a qualcuno che vive per strada.", difficulty: "medium", xp: 2000 },
    { title: "Impara a navigare con le stelle", description: "Studia come orientarsi con le stelle di notte. Poi esci e trovaci il nord senza strumenti.", difficulty: "medium", xp: 2000 },
    { title: "Fai una mezza giornata di pesca in mare aperto", description: "Vai a pesca su una barca al largo per almeno 4 ore. Se prendi qualcosa, cucinalo.", difficulty: "medium", xp: 2000 },
    { title: "Porta a termine un puzzle da 1000 pezzi", description: "Compra o prendi un puzzle da 1000 pezzi e completalo dall'inizio alla fine.", difficulty: "medium", xp: 2000 },
    { title: "Fai una giornata di lavoro completamente offline", description: "Per un'intera giornata lavorativa, disconnetti internet e lavora solo con strumenti locali.", difficulty: "medium", xp: 2000 },
    { title: "Visita una regione italiana che non hai mai visto", description: "Prendi un treno o la macchina e passa almeno un giorno in una regione italiana che non hai mai esplorato.", difficulty: "medium", xp: 2000 },
    { title: "Impara a fare la pasta fresca a mano", description: "Prepara pasta fresca tirata a mano — tagliatelle, pappardelle o ravioli — senza macchina.", difficulty: "medium", xp: 2000 },
    { title: "Partecipa a una battuta di birdwatching", description: "Unisciti a un gruppo di birdwatching o fallo da solo con una guida. Documenta almeno 10 specie.", difficulty: "medium", xp: 2000 },
    { title: "Fai una notte in un ostello con sconosciuti", description: "Prenota un letto in un ostello condiviso e interagisci davvero con chi stai dividendo lo spazio.", difficulty: "medium", xp: 2000 },
    { title: "Segui un'intera giornata di digiuno intermittente 20/4", description: "Mangia tutto in una finestra di 4 ore e digiunna le restanti 20. Solo acqua e tisane fuori dalla finestra.", difficulty: "medium", xp: 2000 },
    { title: "Costruisci una capanna nel bosco", description: "Con rami, foglie e materiali naturali costruisci un rifugio abbastanza solido da poterci sedere dentro.", difficulty: "medium", xp: 2000 },
    { title: "Fai una giornata da artigiano", description: "Trascorri una giornata intera a fare cose con le mani — ceramica, lavorazione del legno, sartoria.", difficulty: "medium", xp: 2000 },
    { title: "Guarda tutti i film di un premio Oscar in un anno", description: "Guarda tutti i film candidati alla miglior pellicola in un anno specifico che non conosci bene.", difficulty: "medium", xp: 2000 },
    { title: "Impara a fare il pane pitta o focaccia", description: "Studia e prepara da zero un pane tradizionale di una cultura diversa dalla tua.", difficulty: "medium", xp: 2000 },
    { title: "Fai un workshop di primo soccorso", description: "Partecipa a un corso base di primo soccorso e impara le manovre fondamentali.", difficulty: "medium", xp: 2000 },
    { title: "Costruisci una cassetta di legno per il giardino", description: "Progetta e costruisci una cassetta porta-piante in legno usando solo strumenti manuali.", difficulty: "medium", xp: 2000 },

    // ── HARD extra ────────────────────────────────────────────────────────────
    { title: "Vivi 30 giorni con meno di 15 euro al giorno", description: "Per un intero mese spendi al massimo 15 euro al giorno per tutto — cibo, trasporti, tutto.", difficulty: "hard", xp: 5000 },
    { title: "Impara a fare lo snowboard — scendi una pista intera", description: "Prendi lezioni di snowboard e riesci a scendere una pista verde dall'alto al basso senza cadute.", difficulty: "hard", xp: 5000 },
    { title: "Scrivi e auto-pubblica un ebook", description: "Scrivi un ebook di almeno 30 pagine su un argomento che conosci e pubblicalo su una piattaforma gratuita.", difficulty: "hard", xp: 5000 },
    { title: "Fai un triathlon sprint", description: "Completa un triathlon sprint: 750m nuoto, 20km bici, 5km corsa. Anche in formato non ufficiale.", difficulty: "hard", xp: 5000 },
    { title: "Trascorri 5 giorni senza parlare con nessuno", description: "Un ritiro di silenzio di 5 giorni, senza conversazioni verbali. Solo scrittura se necessario.", difficulty: "hard", xp: 5000 },
    { title: "Impara a fare una barra fissa (muscle-up)", description: "Allenati fino a riuscire a fare un muscle-up completo alla sbarra da fermo.", difficulty: "hard", xp: 5000 },
    { title: "Organizza un viaggio per altri", description: "Pianifica un viaggio di gruppo per almeno 4 persone: trasporti, alloggi, attività. Gestiscilo tu.", difficulty: "hard", xp: 5000 },
    { title: "Impara a fare lo sci alpino da zero", description: "Prendi lezioni di sci e riesci a scendere una pista blu senza cadute continue.", difficulty: "hard", xp: 5000 },
    { title: "Fai un pellegrinaggio di 5 giorni", description: "Scegli un percorso storico o culturale e percorrilo in 5 giorni con zaino in spalla.", difficulty: "hard", xp: 5000 },
    { title: "Impara la lingua dei segni italiana di base", description: "Studia la LIS fino a riuscire a sostenere una conversazione elementare con una persona non udente.", difficulty: "hard", xp: 5000 },
    { title: "Fai un corso di sopravvivenza avanzato", description: "Partecipa a un corso di wilderness survival di almeno 3 giorni con istruttori certificati.", difficulty: "hard", xp: 5000 },
    { title: "Nuota per un'ora senza fermarti", description: "Completa 60 minuti di nuoto continuo senza mai appoggiarti al bordo vasca.", difficulty: "hard", xp: 5000 },
    { title: "Fai una scalata in falesia multipitch", description: "Completa una via in falesia con almeno 3 tiri di corda su roccia naturale.", difficulty: "hard", xp: 5000 },


    // ── EASY finale ────────────────────────────────────────────────────────────
    { title: "Guarda un film del 1950 o prima", description: "Scegli un film girato prima degli anni 50 e guardalo dall'inizio alla fine senza saltare niente.", difficulty: "easy", xp: 1000 },
    { title: "Passa un'ora a fare niente", description: "Siediti, non fare niente, non pensare a niente di produttivo. Solo esistere per un'ora intera.", difficulty: "easy", xp: 1000 },
    { title: "Vai a dormire alle 22 per tre giorni di fila", description: "Per tre sere consecutive, sii a letto con la luce spenta entro le 22:00.", difficulty: "easy", xp: 1000 },
    { title: "Chiedi a cinque persone cosa pensano davvero di te", description: "Chiedi a cinque persone diverse — amici, familiari, colleghi — una critica onesta su di te.", difficulty: "easy", xp: 1000 },
    { title: "Scrivi una lettera al tuo io di 10 anni fa", description: "Cosa gli diresti? Cosa lo avvertirebbe? Scrivila per intero, come se lui potesse leggerla.", difficulty: "easy", xp: 1000 },
    { title: "Mangia lentamente ogni pasto per una settimana", description: "Per 7 giorni, ogni pasto deve durare almeno 30 minuti. Posa le posate tra ogni boccone.", difficulty: "easy", xp: 1000 },
    { title: "Riorganizza la tua libreria o collezione", description: "Prendi tutti i libri o oggetti della tua collezione, rimettili in ordine e decidi cosa tenere davvero.", difficulty: "easy", xp: 1000 },
    { title: "Fai il punto sulle tue finanze", description: "Siediti e calcola entrate, uscite e risparmi con precisione. Scrivi tutto.", difficulty: "easy", xp: 1000 },
    { title: "Impara a riparare qualcosa che si è rotto", description: "Invece di buttare o comprare nuovo, impara a riparare qualcosa che hai in casa rotto.", difficulty: "easy", xp: 1000 },
    { title: "Prova a disegnare il tuo autoritratto", description: "Siediti davanti allo specchio e disegna il tuo viso nel modo più dettagliato che riesci.", difficulty: "easy", xp: 1000 },
    { title: "Cammina a piedi nudi per la città per un'ora", description: "Esci e cammina a piedi nudi su strade, marciapiedi e prati per almeno un'ora.", difficulty: "easy", xp: 1000 },
    { title: "Scopri la storia di un oggetto antico", description: "Prendi un oggetto vecchio che hai in casa e ricercane la storia: chi lo ha fatto, quando, perché.", difficulty: "easy", xp: 1000 },
    { title: "Fai 20 minuti di respirazione consapevole", description: "Siediti comodamente e pratica tecniche di respirazione consapevole per 20 minuti senza distrazioni.", difficulty: "easy", xp: 1000 },
    { title: "Osserva le formiche per 30 minuti", description: "Trova un formicaio o un sentiero di formiche e osserva il loro comportamento per mezz'ora senza toccarle.", difficulty: "easy", xp: 1000 },
    { title: "Trova e visita il monumento più vicino a casa tua", description: "Cerca qual è il monumento storico più vicino a dove abiti e vai a vederlo davvero.", difficulty: "easy", xp: 1000 },
    { title: "Cucina solo con 5 ingredienti", description: "Prepara un pasto completo usando al massimo 5 ingredienti diversi in tutto.", difficulty: "easy", xp: 1000 },
    { title: "Leggi le news di un paese straniero per un giorno", description: "Invece di leggere news italiane, segui le notizie di un paese straniero per un'intera giornata.", difficulty: "easy", xp: 1000 },

    // ── MEDIUM finale ─────────────────────────────────────────────────────────
    { title: "Percorri una via ferrata", description: "Completa una via ferrata di grado D o E con attrezzatura appropriata.", difficulty: "medium", xp: 2000 },
    { title: "Passa un weekend senza spendere niente", description: "Da venerdì sera a domenica sera, zero spese di qualsiasi tipo. Organizzati in anticipo.", difficulty: "medium", xp: 2000 },
    { title: "Impara a fare grigliatura professionale", description: "Studia le tecniche di griglia — temperature, tagli, tempi — e organizza una grigliata che dimostri quanto hai imparato.", difficulty: "medium", xp: 2000 },
    { title: "Fai un campo base al mare per due giorni", description: "Porta tenda e tutto il necessario e trascorri due giorni in spiaggia dormendo in tenda.", difficulty: "medium", xp: 2000 },
    { title: "Organizza una caccia al tesoro per amici", description: "Progetta e organizza una caccia al tesoro con indizi reali nel mondo fisico per almeno 4 persone.", difficulty: "medium", xp: 2000 },
    { title: "Fai una giornata completa di digiuno digitale", description: "24 ore senza smartphone, computer, tablet o qualsiasi schermo di qualsiasi tipo.", difficulty: "medium", xp: 2000 },
    { title: "Impara a fare la birra artigianale in casa", description: "Segui un kit o una ricetta per produrre birra artigianale in casa. Aspetta i tempi di fermentazione e assaggiala.", difficulty: "medium", xp: 2000 },
    { title: "Esplora una grotta o caverna accessibile al pubblico", description: "Visita una grotta naturale con o senza guida e arriva il più in profondità possibile.", difficulty: "medium", xp: 2000 },
    { title: "Scrivi un diario di viaggio illustrato", description: "Durante o dopo un viaggio, crea un diario che combini scritto e disegni per raccontare l'esperienza.", difficulty: "medium", xp: 2000 },
    { title: "Impara a fare una riparazione di bici da zero", description: "Impara a smontare, pulire e rimontare la trasmissione di una bici senza portarla in officina.", difficulty: "medium", xp: 2000 },

    // ── HARD finale ───────────────────────────────────────────────────────────
    { title: "Completa una settimana di allenamento militare", description: "Segui per 7 giorni un programma di allenamento ispirato a quello militare: alzata all'alba, corse, esercizi a corpo libero.", difficulty: "hard", xp: 5000 },
    { title: "Impara a fare il front lever", description: "Allenati fino a riuscire a tenere il front lever alle sbarre per almeno 3 secondi.", difficulty: "hard", xp: 5000 },
    { title: "Fai un viaggio in solitaria di 10 giorni all'estero", description: "Organizza e completa un viaggio di 10 giorni in un paese straniero completamente da solo.", difficulty: "hard", xp: 5000 },
    { title: "Impara a fare free solo bouldering", description: "Raggiungi un livello di arrampicata boulder che ti permetta di completare un percorso V3 o superiore.", difficulty: "hard", xp: 5000 },
    { title: "Costruisci un sito web da zero senza tutorial copia-incolla", description: "Crea un sito funzionante partendo da zero, senza copiare codice da tutorial. Studia, capisci, scrivi.", difficulty: "hard", xp: 5000 },
    { title: "Pratica un mese di astinenza da qualcosa che usi ogni giorno", description: "Scegli qualcosa che usi quotidianamente — caffè, social, alcolici, TV, carne — e smetti per 30 giorni esatti.", difficulty: "hard", xp: 5000 },
    { title: "Fai un cammino in solitaria di almeno 7 giorni", description: "Percorri un itinerario a piedi multi-giorno completamente da solo, dormendo in tenda.", difficulty: "hard", xp: 5000 },

    { title: "Fai il bagno in un laghetto di collina", description: "Trova un laghetto naturale di collina o pianura e immergiti completamente, anche in autunno.", difficulty: "easy", xp: 1000 },
    { title: "Scrivi un haiku per ogni ora del giorno", description: "Dalla mattina alla sera, scrivi un haiku ogni ora che passa. Alla fine avrai un ritratto della giornata.", difficulty: "easy", xp: 1000 },
    { title: "Testa il tuo senso dell'orientamento", description: "Vai in un posto che conosci, bendati, fatti girare e poi cerca di indicare dove si trova il nord.", difficulty: "easy", xp: 1000 },
    { title: "Fai una giornata di turismo nella tua città", description: "Visita la tua città come la visiterebbe un turista straniero alla prima visita.", difficulty: "easy", xp: 1000 },
    { title: "Fai un'ora di raccolta di erbe spontanee", description: "Con una guida alle erbe commestibili, esci in campagna e raccogli quello che trovi. Cucinalo.", difficulty: "easy", xp: 1000 },
    { title: "Scrivi la tua visione di futuro per i prossimi 5 anni", description: "Mettiti a scrivere dove ti vedi tra 5 anni in tutti gli aspetti della vita. Sii specifico.", difficulty: "easy", xp: 1000 },
    { title: "Impara a fare tre magie semplici", description: "Impara tre trucchi di magia da fare con le mani o un mazzo di carte. Mostrali a qualcuno.", difficulty: "easy", xp: 1000 },
    { title: "Fai un'escursione in bici su un sentiero sterrato", description: "Porta la bici fuori asfalto e percorri almeno 10 km su sterrato, single track o sentiero.", difficulty: "medium", xp: 2000 },
    { title: "Impara a fare il formaggio in casa", description: "Segui una ricetta per fare il formaggio in casa — ricotta, primosale o mozzarella — dall'inizio alla fine.", difficulty: "medium", xp: 2000 },
    { title: "Fai un'uscita in kayak di mare", description: "Percorri almeno 10 km in kayak in mare aperto, anche con istruttore.", difficulty: "medium", xp: 2000 },

    // ── SEASONAL QUESTS ────────────────────────────────────────────────────────

    // WINTER
    { title: "Costruisci un pupazzo di neve", description: "Esci con la neve e costruisci un pupazzo vero, con dettagli e personalità.", difficulty: "easy", xp: 1000, category: "natura", season: "winter" },
    { title: "Fai una passeggiata nella neve di notte", description: "Esci dopo le 22 con la neve al suolo e cammina per almeno 30 minuti nel silenzio invernale.", difficulty: "easy", xp: 1000, category: "natura", season: "winter" },
    { title: "Fai il bagno in un fiume ghiacciato", description: "Immergiti in un corso d'acqua invernale freddo per almeno 10 secondi. Sicurezza prima di tutto.", difficulty: "hard", xp: 5000, category: "sfida", season: "winter" },
    { title: "Dormi con la finestra aperta in pieno inverno", description: "Una notte intera con la finestra aperta. Zero riscaldamento, solo coperte.", difficulty: "medium", xp: 2000, category: "sfida", season: "winter" },

    // SUMMER
    { title: "Dormi sulla spiaggia fino all'alba", description: "Passa la notte su una spiaggia e aspetta il sorgere del sole senza dormire al chiuso.", difficulty: "medium", xp: 2000, category: "natura", season: "summer" },
    { title: "Nuota fino a un punto lontano dalla riva", description: "Nuota in mare aperto fino a un punto dove non tocchi e sei lontano dalla spiaggia. Con sicurezza.", difficulty: "hard", xp: 5000, category: "sport", season: "summer" },
    { title: "Fai un'escursione di notte in estate", description: "Scegli un sentiero che conosci e percorrilo di notte con solo una torcia frontale.", difficulty: "medium", xp: 2000, category: "natura", season: "summer" },
    { title: "Passa un'intera giornata all'aperto senza entrare mai in casa", description: "Dalla sveglia al tramonto, zero interni. Mangia fuori, lavora fuori, riposati fuori.", difficulty: "medium", xp: 2000, category: "sfida", season: "summer" },

    // SPRING
    { title: "Pianta qualcosa e prenditi cura finché non cresce", description: "Pianta un seme o una piantina e seguila ogni giorno finché non vedi la crescita visibile.", difficulty: "easy", xp: 1000, category: "natura", season: "spring" },
    { title: "Fai un'escursione all'alba di primavera", description: "Svegliati prima del sole in un giorno di primavera e raggiungi un punto panoramico per l'alba.", difficulty: "medium", xp: 2000, category: "natura", season: "spring" },

    // AUTUMN
    { title: "Raccogli funghi con un esperto", description: "Accompagna un esperto nella raccolta di funghi in autunno. Impara a distinguere almeno 5 specie.", difficulty: "medium", xp: 2000, category: "natura", season: "autumn" },
    { title: "Fai un falò autunnale con gli amici", description: "Organizza una serata attorno a un falò in un posto autorizzato. Niente telefoni per almeno 2 ore.", difficulty: "easy", xp: 1000, category: "sociale", season: "autumn" },

    // WEEKEND ONLY
    { title: "Svegliati prima di tutti nel weekend", description: "Di sabato o domenica, svegliati entro le 6:00 e fai qualcosa di produttivo prima che gli altri si alzino.", difficulty: "easy", xp: 1000, category: "sfida", season: "weekend" },
    { title: "Organizza un'attività di gruppo spontanea", description: "Manda un messaggio a 5+ persone proponendo qualcosa per oggi pomeriggio. Vai avanti comunque.", difficulty: "medium", xp: 2000, category: "sociale", season: "weekend" },
    { title: "Fai un'escursione last minute", description: "Scegli una destinazione, prepara lo zaino in 20 minuti e parti entro un'ora dalla decisione.", difficulty: "medium", xp: 2000, category: "natura", season: "weekend" },
];
